export const lorem01 =
`<p>Lorem ipsum dolor sit amet, ac netus leo pede commodi ut, vitae mauris vitae non hendrerit fringilla erat. Integer dolor facilisis, congue suscipit, amet odio etiam curae fermentum sodales. Velit nascetur nullam in mauris diam. Neque nec feugiat, libero luctus et, velit erat nibh. Quisque ligula, ante penatibus.</p>

<p>Ipsum nunc nulla fusce nulla gravida. Amet fringilla, diam eget ante commodo eros wisi. Nisl est sem scelerisque ante nullam, a nec pede, hendrerit id. In justo vestibulum tristique egestas et fermentum, scelerisque lobortis feugiat vestibulum, purus ut faucibus, nunc ac. Nisl sodales nulla, orci sit vitae suspendisse, lacus ut mi amet orci, nec sagittis lacus nascetur. Habitant vel, ut lectus et ut, facilisis vel, vivamus neque sed ut nunc pede. Tellus duis ea id habitant, id laoreet vulputate fringilla vel aenean eget, fermentum nam volutpat in quam ipsum suspendisse. Pellentesque bibendum ut, dolor in vulputate et, imperdiet ut ipsum ut ligula euismod elit, eu tellus et libero risus taciti, augue sed quis justo risus eu dui. Dictum arcu purus neque rhoncus dapibus neque, commodo ut donec.</p>

<p>Augue arcu tincidunt, nonummy taciti, risus magnis non tellus vel, dolor sem elementum convallis. Interdum neque urna, consequat vel in libero urna integer odio, lacus vivamus nunc donec amet nullam, urna cursus pellentesque et sociis, eros tortor sed lacus feugiat. Sollicitudin nibh hymenaeos elit non, lectus vitae ac amet facilisis, blandit nibh aliquam diam erat in ipsum. Habitant occaecat erat lorem interdum, aenean elit scelerisque volutpat in ultricies, vivamus facilisis nec, suscipit ullamcorper erat platea commodo aliquid, ultricies non est enim quam. Risus vel diam, ad vitae duis commodo, lectus fusce, ut proin sed. Eligendi egestas vel eum lacinia in, in lobortis massa.</p>

<p>Sapien mi ac. In duis wisi posuere, felis accumsan aliquam sit nulla vitae, in lacus lectus justo, dui ornare aliquet sit nobis non dictum. Maecenas ut commodo ac massa sagittis enim, aliquet quisque justo metus vel, eget luctus mattis et lorem nec purus, pede etiam felis, odio donec velit dui scelerisque et. Suspendisse arcu porttitor non rutrum aliquet sed, donec ut pulvinar at nec sed, vulputate et fringilla id semper velit sit, ipsum id pellentesque fringilla eu ut, ipsum ac. Quis a praesent, nulla ut nibh bibendum, tempus hymenaeos, arcu tellus ultrices integer consectetuer nullam, ligula sed sed pede malesuada sapien. Imperdiet ante pellentesque sapien vulputate et morbi, convallis consequat suscipit nec, at amet, pulvinar excepteur eros faucibus, elementum lectus est viverra. Quisque pulvinar cras curabitur sociosqu, lacinia elementum elit et dui semper. Feugiat risus massa amet. Donec id mus sem urna et, nulla mollis nunc magna tellus sodales enim, rhoncus amet dui pede voluptatibus, metus erat sed in odio, libero occaecati sodales convallis sapien vulputate. In volutpat, amet donec, pellentesque eget. Nunc quam per arcu, nullam rhoncus, pharetra id nisl quisque eu in mattis, praesent dui eu massa class mauris.</p>
`;
